workflows:
  print_ip:
    name: Print Public IP
    instance_type: mac_mini_m2
    scripts:
      - name: Fetch and print public IP
        script: |
          echo "Fetching public IP address..."
          curl http://checkip.amazonaws.com
          echo "Done."
